### PR TITLE
patch: Iron Maiden Virtual Time (Original 2020)

### PR DESCRIPTION
**Pull request by francisdb**
https://vpuniverse.com/files/file/6257-iron-maiden-virtual-time-imvt/page/3/?tab=comments

Tried to get the music to work but got this:
https://github.com/vpinball/vpinball/issues/1191

wine issue: https://bugs.winehq.org/show_bug.cgi?id=55093

### CODE REVIEW

**Comment by francisdb** [comment]
@jsm174 this one can be merged.

**Comment by toccata10** [comment]
As a workaround, I was hoping to get the music work by using the pup pack version of the table:
https://vpuniverse.com/files/file/6383-iron-maiden-virtual-time-pup-pack-12-normal-and-fulldmd/
As it says (in "About this File"): 'Also you can add as many musics as you want inside the folder "MusicVideos" with this pup pack I have 8 already. '
But this table crashes and I don't have the skills to fix it. So, no idea if it works (it might work as puppack has a different mecanism to load random files from a folder).

**Comment by francisdb** [comment]
gerhard_b came up with this for music

image

**Comment by francisdb** [comment]
@jsm174 this can be merged

**Pull request merged**
