### PR TITLE
patch: Saving Wallden

### PR DESCRIPTION
**Pull request by francisdb**
https://vpuniverse.com/files/file/20304-saving-wallden/

If you start this table in cab mode you will see a big gray square, re-center the table using the tweak menu.

Typical 2-dimensional array access issues.

### CODE REVIEW

**Comment by Lovinity** [comment]
(This is Arelyel) I appreciate this. However, this seems like an issue with VPX standalone. Why can't the devs of VPX standalone fix this issue?

I'd rather not break vbscript conventions to work around another software's bugs unless it's impossible to fix.

**Comment by jsm174** [comment]
@Lovinity - I 100% understand your concerns.  Unfortunately we've spent countless hours (no joke) trying to figure out a fix. 

I'm not sure how familiar you are with standalone, but we are using the vbscript engine source code from wine and it has some quirks.

We have it down to now to just a laundry list of workarounds: https://github.com/vpinball/vpinball/blob/10.8.1/standalone/vbscript.md

None of these workarounds are breaking any "vbscript" conventions.

That said, we have been extremely fortunate that so many table authors have embraced standalone and have made changes when needed.

I know this isn't a great answer, but I hope it explains things a little better.

**Comment by Lovinity** [comment]
@jsm174 I'm only vaguely familiar with it. I do know it's a stand-in using WINE to run VPX tables in non-Windows operating systems. But that's as far as I know.

I would love to be one of those authors. But unfortunately, unlike most authors, I am the sole developer of the table. And furthermore, I have very little available time to work on it. So I have to make some compromises so this project doesn't end up taking 10 years like I'm currently estimating at my rate. 

If someone is willing to help maintain VPX standalone compatibility for the table, that would be amazing. I'll eventually merge in what you got (I already merged the vpwMusic and vpwTracks portions since those were external scripts; everything above line 14863). And I'll add you in as a contributor and list you under VPX standalone compatibility fixes.

**Comment by francisdb** [comment]
Understand your concerns that these issues might creep back in during further table development. I'm ok with keeping this patch updated as new versions are released.

**Comment by Lovinity** [comment]
@francisdb Sounds good, and I appreciate it! I'm not in VPW at the moment though. I'm on VPUniverse and in the Virtual Pinball Chat Discord.

(Also please ignore the recent release announcements / updates of the table that went out today; I merely changed the description on the download lol; there is no actual update)

**Comment by francisdb** [comment]
Ah then ping me in #vpx-standalone on vpc or with a pm.

**Pull request merged**
