### PR TITLE
dmd_hack: X-Files (Sega 1997) v1.29

### PR DESCRIPTION
**Pull request by toccata10**

### CODE REVIEW

**Comment by jsm174** [comment]
for some reason I see a `Student Prince (Williams 1968).vbs.original` file in this PR

**Comment by toccata10** [comment]
Yes, it's super strange (to me): I didn't touch those "student prince" files.
And it's getting worse in my new testing:
```
gh repo clone toccata10/vpx-standalone-scripts
cd vpx-standalone-scripts
git checkout -b xfiles3
git commit -a
```
Screenshot from 2024-02-04 08-28-47

gives me:
```
[xfiles3 36750cd] dmd_hack: xfiles
 2 files changed, 16 insertions(+), 16 deletions(-)
```
Surely @francisdb can share some ligth on this github mystery (for me)

**Comment by francisdb** [comment]
If files are pulled in as changed they are in the repo in the wrong format.

Student prince was a disaster regarding line endings but I think I already fixed that. Will have a look tomorrow.

**Comment by jsm174** [comment]
I think you just need to remove the student price file from this PR, and we can merge

**Comment by jsm174** [comment]
@toccata10, you just need to remove the file all together from this PR. 

Screenshot 2024-02-05 at 8 35 18 AM

**Comment by toccata10** [comment]
I think that's ok now.

**Pull request merged**
