### PR TITLE
patch: Beavis and Butt-head_Pinballed

### PR DESCRIPTION
**Pull request by francisdb**
https://vpuniverse.com/files/file/18299-beavis-and-butt-head-pinballed-bally-1993/

Reported to table author here:
https://vpuniverse.com/forums/topic/9903-new-vp10-alert-beavis-and-butt-head-pinballed-bally-1993/?do=findComment&comment=78352

### CODE REVIEW

**Comment by jsm174** [comment]
nice catch. Went to try this one, worked great on mac, but crashed on linux. Didn't have any time to look into it.

**Comment by francisdb** [comment]
I do find it strange that nothing is failing when the file is not found.

**Comment by jsm174** [comment]
Nothing strange, the code doesn't log any messages if `GetTextFile` can't find a file:

https://github.com/vpinball/vpinball/blob/65b50dbb640a4760583c81da3b943c74de688cb1/src/parts/pintable.cpp#L456-L552

I'll add some info entries, next time I get to it.

**Comment by zognic** [comment]
> nice catch. Went to try this one, worked great on mac, but crashed on linux. Didn't have any time to look into it.

Works fine here on batocera (and osx too)

**Comment by francisdb** [comment]
> Nothing strange, the code doesn't log any messages if `GetTextFile` can't find a file:
> 
> https://github.com/vpinball/vpinball/blob/65b50dbb640a4760583c81da3b943c74de688cb1/src/parts/pintable.cpp#L456-L552
> 
> I'll add some info entries, next time I get to it.

Somehow the script expects an exception to be thrown?
https://github.com/vpinball/vpinball/blob/65b50dbb640a4760583c81da3b943c74de688cb1/scripts/controller.vbs#L157-L163

**Pull request merged**
