### PR TITLE
Fix Medieval Madness bridge not closing

### PR DESCRIPTION
**Pull request by Nicals**
Controller.GetMech(0) ([here](https://github.com/jsm174/vpx-standalone-scripts/blob/ebd36426fa30f4b6950369f6aaa55e9e1fb6983a/1455577933_MedievalMadness_Upgrade(Real_Final)/1455577933_MedievalMadness_Upgrade(Real_Final).vbs.original#L1379)) was returning 0 every time, this commit fixes the castle bridge not closing.

It seems that some people have issue with this on Windows too. I 'm not sure if this issue is related to Linux users only or is more global.

### CODE REVIEW

**Comment by francisdb** [comment]
Not sure we want to fix table logic here. Might be better to report this in the support section of the table?

Do you have a link to the location where the table can be downloaded?

**Comment by Nicals** [comment]
I wasn't sure either it was the right place. I had an item on my TODO list to try and get in touch with the author of the table. This will be my next step.

I understand if this is not the right place for such a fix.

**Comment by jsm174** [comment]
@Nicals - Thanks.  Just curious is this with B2S on, or just VPinMAME by itself?

**Comment by Nicals** [comment]
I'm not totally familiar with VPinball ecosystem. I only ran it using the standalone without any other utility. I assume this would mean that it is VPinMAME by itself.

**Comment by jsm174** [comment]
@Nicals - kudos for finding this issue!

libpinmame had a different way of notifying of mech changes. `mm` is even more unique as mech 0 is not using the standard `mech_add` logic.

Since we want standalone to be compatible (as much as possible), I implemented a `PinmameGetMech()` function [here](https://github.com/vpinball/pinmame/commit/8539587ab43d0fc99148eca10185b9d35cbe32d6#diff-8a462bd03d3bf6c08c973486276d05939e4c4d85a04ae02a97210c60ab600b38R988).

Standalone has been updated to take advantage of this new function, so `mm` should now work without a patch:

https://github.com/jsm174/vpx-standalone-scripts/assets/1197137/14005784-7f68-4512-abc2-c90291f2296b

**Pull request closed without merging**
