### PR TITLE
patch: Alien Nostromo 4.0 (Original 2020) Ultimate

### PR DESCRIPTION
**Pull request by francisdb**
Not the most elegant patch but a minimum one

https://bugs.winehq.org/show_bug.cgi?id=54978

### CODE REVIEW

**Comment by jsm174** [comment]
Anywhere you added the colon, can it be consistent. ie a few have `: ` while others are just `:`

Can you add one between End:

`Sub SFX4_hit() :PlaySound "Door" End Sub`

Since the colons were added on the other ones between `End`?

**Comment by francisdb** [comment]
@jsm174 this should no longer be required in latest wine?

**Comment by francisdb** [comment]
Patch no longer required

**Comment by jsm174** [comment]
Cool. Again sorry for the extra work on this one. 😥

**Pull request closed without merging**
