### PR TITLE
patch: fireballIIVPX

### PR DESCRIPTION
**Pull request by francisdb**
Typical patch create with vpxtool

https://vpuniverse.com/files/file/9242-fireball-ii/

### CODE REVIEW

**Comment by jsm174** [comment]
@francisdb - should the parent directory be `fireball II VPX` to match the vpx filename?

**Comment by francisdb** [comment]
I normally match the zip file name but can change to vpx file name from now on.

**Comment by jsm174** [comment]
yeh, I think 99% of them are the name of the vpx file. If you can fix this one, I'll merge.

**Comment by francisdb** [comment]
@jsm174 done, please squash on merge

**Pull request merged**
