### PR TITLE
patch: Fish Tales (Williams 1992)_JLMD Edition v0.8

### PR DESCRIPTION
**Pull request by francisdb**
https://www.vpforums.org/index.php?app=downloads&showfile=15741

I did have some other issue with repeating sound when locking the ball

### CODE REVIEW

**Comment by francisdb** [comment]
Looks like this behaves differently than on windows

`nHole = Controller.GetMech(1)    'Return which Ball Lock is UP!` returns 0 and expects 1-3 and goes to the broken code
then it loops that part causing the contained audio sample repeat

**Comment by francisdb** [comment]
Sounds like this is a similar issue to https://github.com/vpinball/pinmame/commit/e4f1a214bdfe5cfe305c258d6739178858d15175 ?

**Comment by francisdb** [comment]
Some unreleased newer version of this table also has issues related to the lock ball spinner. Probably has something to do with recent pinmame changes

[Screencast from 2024-01-23 15-25-27.webm](https://github.com/jsm174/vpx-standalone-scripts/assets/161305/ffc392e9-14b2-44db-be0d-09f1d539b4ee)

**Comment by jsm174** [comment]
I just debugged the code with the latest pinmame for this specific version of the table.

It's definitely getting into the right place inside of pinmame:

```
static int ft_getMech(int mechNo) {
  switch (mechNo) {
	//Return Reel Position
	case 0: return locals.reelPos;
	//Return Which Ball Lock is UP in Reel Position!
	case 1:
		if(locals.reelPos>=BALL1UP && locals.reelPos<=BALL1UP+ERROR_RANGE)
			return 1;
		if(locals.reelPos>=BALL2UP && locals.reelPos<=BALL2UP+ERROR_RANGE)
			return 2;
		if(locals.reelPos>=BALL3UP && locals.reelPos<=BALL3UP+ERROR_RANGE)
			return 3;
		return 0;
  }
  return 0;
}
```

**Comment by jsm174** [comment]
I don't see this happen all the time as well:

When it gets stuck in that loop where we keep hearing a solenoid firing, 

BALL1UP is 0
BALL2UP is 50
BALL3UP is 100
ERROR_RANGE is 10

in `ft_getMech`:

`reelPos` = 90

```
90 >= 0 && 90 <= 0 + 10
90 >= 50 && 90 <= 50 + 10
90 >= 100 && 100 <= 100 + 10
```

None of these conditions pass so it returns 0

When it gets into 

```
    if (core_getSol(sReelMotor))
      locals.reelPos++;
```

Solenoid 28 isn't enabled, so `reelPos` is never advanced.

**Comment by jsm174** [comment]
Or maybe its just a flaw in the table logic, ie they keep checking mech 1 over, maybe its somewhere earlier in the table. The newer version never makes a direct call to `GetMech`

**Comment by jsm174** [comment]
If we look at the table code: 

```
Sub ReelEnter_Hit() 	
  Dim nHole
    Stopsound "metal"
	PlaySound "hop2"
	Me.DestroyBall
	nHole = Controller.GetMech(1)	'Return which Ball Lock is UP!
	'Which hole is UP?
	Select Case nHole
		Case 1
			bsReel1.AddBall 0
		Case 2
			bsReel2.AddBall 0
		Case 3
			bsReel3.AddBall 0
		Case Else
		     'No hole up, we'll call this method again in 500 ms, and try again!
		     VPMTimer.AddTimer 500,"ReelEnter_Hit '"
	End Select	 
End Sub
```

`GetMech(1)` is calling the correct code in pinmame, but if it returns 0, its going to call over and over and over, playing "hop2" sound.

I really think there is an issue with the table code. it should be looking at solenoid 28 as well as `GetMech(1)`

**Comment by francisdb** [comment]
Closing this one, I suggest using https://vpuniverse.com/files/file/18293-fish-tales-vpw/ instead

**Comment by Waitsnake** [comment]
Its a pity if you gave up on those Fish Tales tables in vpforums so easily especially since the linked alternative table from vpuniverse its: "This table is pushing the limits.".
For me the table from vpuniverse is not working at all, neither on Windows nor on macOS with the VPX 10.8 betas (on macOS I not even have the mentioned Tweak Menu). For me those tables are no alternative at all. But I did a short look into the script of the vpuniverse table and it basically completely ignores the simulation in "ft.c" and simulates all inside the VBS script, even the controlling of the optocoupler directly.


I looked into one of those tables from vpforums, especially "Fish Tales (Williams 1992)_Bigus(MOD) 2.2" since it is the newest looking of them (but all tables vpforums handle the reel the same way).
The VBS script is maybe not optimal like it is not distinguishing between the ball hit event (sub ReelEnter_Hit) and the "repeat event" where it just call sub ReelEnter_Hit again after 500ms to put the ball either in  bsReel1, bsReel2 or bsReel3. Because of repeating ReelEnter_Hit the "hop2" sound again and again (because "ft.c" simulation is to fast for its sampling to add a ball in the first place) ...
But this is an easy fix in the VBS script and I coded a separate sub e.g. ReelEnterTimer that not plays the "hop2" sound again and just try to poll on Controller.GetMech(1) that gives back which enter-hole is up or if it is in between the the holes.
You get not back directly which exit-hole is "down" (actually it is more 270° on the wheel than 180° to reach the catapult and "down" is a bit misleading) to throw the ball to the catapult. The "down"/exit event is handled by the callback definitions SolCallback(51-53) that are connected to "bsReel1-3.SolOut". Sub bsReel1.SolOut can of cause only throw out a ball if there was a ball added with sub bsReel1.AddBall before, either in ReelEnter_Hit or ReelEnterTimer. The sample rate of repeat of adding a ball to bsReel1-3 was original with 500ms a bit low and so I changed it to 50ms. With this the table worked with Visual Pinball v10.7.2 for Windows decent.

But with Visual Pinball v10.8.0 Beta Standalone on macOS it was still not working with my VBS improvements. So I looked into the source code of "ft.c" from pinmame you mentioned here earlier.

I found out that Controller.GetMech(0) gives back the angle where the wheel is between 0-150 (not 0°-360°, but can be easy converted) and could use this information in VBS directly to determinate what "up"/entry position is ready or what "down"/exit position is ready. But still the results I had on macOS were all over the place.
It was like the simulation inside "ft.c" was way faster than the VBS would sample it with 50ms. Which seems to be the core problem here apart from the suboptimal original VBS table script. 
On the a typical rotation of the wheel complete states were missing when sampling with 50ms since "ft.c" runs faster.

And when we are looking on the rotation order from 0-150 that is implemented in "ft.c" simulation: Ball1Entry-> **Ball3Exit**->Ball2Entry->**Ball1Exit**->Ball3Entry->**Ball2Exit** I wonder are the exit events (or "ball down" events) not wrong? 
When 1st ball is entered in hole 1 and 2nd ball in hole 2 the 1st ball would already eject to catapul when motor moves to Ball3Entry since it passed Ball1Exit on the way and this before a 3rd ball can enter at all. Normally entry of 3rd ball should trigger the multi ball and so 1st ball should not shoot before.
I think "ft.c" should handle the order from 0-150 for the event like this: Ball1Entry-> **Ball2Exit**->Ball2Entry->**Ball3Exit**->Ball3Entry->**Ball1Exit**. Otherwise it can shoot balls too early before the multi ball starts.

So I tried to get the angle of the wheel angle directly(via Controller.GetMech(0)) and handled the Entry/Exit events directly in my changed VBS script changed the rotation to the suggested: Ball1Entry-> Ball2Exit->Ball2Entry->Ball3Exit->Ball3Entry->Ball1Exit. 

Then I patched "ft.c" and added a "quick and dirty" "frame limiter" inside the simulation, so that not each ft_handleMech() call from "core.c" advances locals.reelPos by one position.

```
static void ft_handleMech(int mech) {

    /* ... */

    /* -- If Reel Motor Turning Rotate Position! --*/
    if (core_getSol(sReelMotor))
    {
        locals.limiter--;
        if (locals.limiter == 0)
        {
           locals.reelPos++;
           locals.limiter = FRAME_LIMITER;
        }
    }
  }
```
I experimented and **10** was a good value there for FRAME_LIMITER on **my** Mac .

But doing a static delay like this is of cause no perfect solution to keep the "ft.c" simulation in sync with VB scripts on **any** system and for the future. Maybe there is a better way to do it and making the delay of simulation relative to vblank signal or a time delay? I'm too unexperienced within pinmame code to know to make my "quick and dirty" solution better.

To wrap it up I think I see 3 issues here:
1) "ft.c" simulation is way too fast for VB script based sampling and already adding the balls fails in VBC
2) "ft.c" simulation seems to have the order on the 0-150 wheel wrong for the "down" events and can shoot SolOut events for some balls early (if the VBC manages it at all to add randomly add a ball in the first place because of 1) )
3) the VBS scripts are suboptimal coded and can be improved too


I hope you give the Fish Tales tables in vpforums another chance by improving on the "ft.c" simulation, then maybe the authors of those tables have a chance to improve their VBS scripts.

**Comment by francisdb** [comment]
@Waitsnake Thanks for the thorough research but it would be better to report your findings at https://github.com/vpinball/pinmame where that `ft.c` is being managed. All we do in the `vpx-standalone-scripts` repo is creating specific patches for scripts that fail to run on standalone. We try to stay away from optimizations or changes in game logic as those are for the table creators to tackle.

I do believe that github repositories for tables would be great for collaborating/reviewing/history on table scripts.
eg https://github.com/francisdb/vpw-example-table-extracted

**Pull request closed without merging**
