### PR TITLE
New Medieval Madness table (the other MM has an issue)

### PR DESCRIPTION
**Pull request by lbrpdx**
The other Medieval Madness table in the repo seems to have a problem with the drawbridge not working properly. This table works fine for me.

### CODE REVIEW

**Comment by lbrpdx** [comment]
https://vpuniverse.com/files/file/18223-medieval-madness-williams-1997_vr-special-edition/

**Comment by jsm174** [comment]
this seems to have a few more additions. are they really necessary?

**Comment by lbrpdx** [comment]
What do you mean? 
Is there another MM table that works with standalone VPX? Because this one does, is pretty (although heavy, I agree) but at least the game is fully playable. The drawbridge doesn’t with https://github.com/jsm174/vpx-standalone-scripts/tree/master/1455577933_MedievalMadness_Upgrade(Real_Final)

**Comment by jsm174** [comment]
@lbrpdx - sorry I looked at it to quickly. I saw the outside +'s and was thinking you were adding `Lights(14) = ...`. 

apologies!

Screenshot 2024-06-11 at 7 27 14 AM

**Comment by jsm174** [comment]
@lbrpdx - So I went to merge this, but the table downloaded from the link above is:

Medieval Madness (Williams 1997)_DarthVito_VR SE.vpx

We've been trying to keep the patch filenames the same as the downloaded file to avoid confusion.

**Pull request closed without merging**
