### PR TITLE
patch: Thunderbirds original 2022 v1.0.2

### PR DESCRIPTION
**Pull request by francisdb**
https://vpuniverse.com/files/file/10465-thunderbirds-original-2022/

These are the changes in flex dmd file name casing I found. Hope I found all.

### CODE REVIEW

**Comment by francisdb** [comment]
This is what the screenshot on the web page shows

image

I guess you'll need to set up a wider window.
Or go in windows vpx editor and move the dmd.
Or enable the external flexdmd window and use that.

**Comment by francisdb** [comment]
The default window created here is 

```
2024-02-06 14:24:00.308 INFO  [375257] [Player::CreateWnd@492] Creating main window
2024-02-06 14:24:00.341 INFO  [375257] [Player::CreateWnd@554] SDL display mode: 1024x576 60Hz SDL_PIXELFORMAT_RGB888
```

**Comment by zognic** [comment]
thanks, I moved the FlexDMD on windows

`2024-02-06 14:33:51.805 INFO  [14063] [VP::Window::Window@35] Window created: title=FlexDMD, size=290x75, pos=15,333, z=200`

**Comment by jsm174** [comment]
Hello. Is this one now working correctly in the latest releases?

**Comment by zognic** [comment]
> Hello. Is this one now working correctly in the latest releases?

so far so good

**Comment by francisdb** [comment]
Ok for merge

**Pull request merged**
