### PR TITLE
patch: Three Angels (Original 2018) 1.3

### PR DESCRIPTION
**Pull request by francisdb**
This must be the craziest table out there. 100.000+ lines of VBScript code

https://vpuniverse.com/files/file/11197-three-angels/

Currently no DMD visible

### CODE REVIEW

**Comment by francisdb** [comment]
@jsm174 also having issues to show a DMD on this one

**Comment by jsm174** [comment]
If this table uses UltraDMD, I'm not done porting over the FlexDMD port of UltraDMD.

**Comment by francisdb** [comment]
@jsm174 mind having a look why the dmd is not working

Even with `ImplicitDMD_Init` and `ImplicitDMD_Timer`

Here is some footage
https://www.youtube.com/watch?v=MCKNaU16gDM

**Comment by jsm174** [comment]
So I had to run this one through the debugger. For some reason the width and height of the DMD were always 0.

So VPX has built in functions registered as `DMDHeight` and `DMDWidth`:

https://github.com/vpinball/vpinball/blob/f1eeee70e6d337df1231206ab97416e3d42e5cd6/pintable.cpp#L1109-L1121

```
STDMETHODIMP ScriptGlobalTable::put_DMDWidth(int pVal)
{
   if (g_pplayer)
      g_pplayer->m_dmd.x = pVal;
   return S_OK;
}


STDMETHODIMP ScriptGlobalTable::put_DMDHeight(int pVal)
{
   if (g_pplayer)
      g_pplayer->m_dmd.y = pVal;
   return S_OK;
}
```

After reviewing the table script:

```
Dim DMDColor, DMDColorSelect, UseFullColor
Dim DMDPosition, DMDPosX, DMDPosY, DMDSize, DMDWidth, DMDHeight


UseFullColor = "True" '                           "True" / "False"
DMDColorSelect = "Red"            ' Rightclick on UDMD window to get full list of colours

DMDPosition = False                               ' Use Manual DMD Position, True / False
DMDPosX = 5763                                   ' Position in Decimal
DMDPosY = 40                                     ' Position in Decimal

DMDSize = False                                     ' Use Manual DMD Size, True / False
DMDWidth = 1276                                    ' Width in Decimal
DMDHeight = 684                                   ' Height in Decimal
```

It's using variables called `DMDWidth` and `DMDHeight` which seem to mask the built in functions. I renamed all `DMDWidth` to `DMD_Width` and `DMDHeight` to `DMD_Height` and the DMD shows as expected:

Screenshot_2023-07-23_at_5 32 06_PM

**Comment by francisdb** [comment]
So this masking does not happen on windows?

**Comment by jsm174** [comment]
Correct. Somehow Windows vbscript must realize its a function call vs a variable. Maybe internally they iterate functions before variables, IDK.

**Comment by francisdb** [comment]
These two still fail, is that expected?

```vbscript
WshShell.RegWrite "HKCU\Software\UltraDMD\fullcolor",UseFullColor,"REG_SZ"
WshShell.RegWrite "HKCU\Software\UltraDMD\color",DMDColorSelect,"REG_SZ"
```

**Comment by jsm174** [comment]
Yes. I don't know if we should ever support `WshShell` COM object. So many things to say about tables that use it...

Are you ready to merge this?

**Comment by francisdb** [comment]
I would say so yes, we can always tweak more later if needed

**Pull request merged**
