### PR TITLE
IT Pinball Madness (JP Salas,Joe Picasso)1.2

### PR DESCRIPTION
**Pull request by francisdb**

### CODE REVIEW

**Comment by francisdb** [comment]
I wonder what this `Default` should be. And why this does not fail on windows.

**Comment by jsm174** [comment]
Is this one ready? Default is a keyword and used in classes.

**Comment by francisdb** [comment]
> Is this one ready? Default is a keyword and used in classes.

Then this probably needs a fix on the side of vpinball?

**Comment by francisdb** [comment]
```
2023-06-24 10:09:45.311 ERROR [942058] [CodeViewer::OnScriptError@1176] Script Error at line 8869 : VBSE_OLE_NO_PROP_OR_METHOD
2023-06-24 10:09:45.311 ERROR [942058] [CodeViewer::AppendLastErrorTextW@3950] Compile error: Line: 8869, Character: 0, VBSE_OLE_NO_PROP_OR_METHOD
```

image

**Comment by jsm174** [comment]
According the grammar, I guess it should be okay as a variable. 

```
/* these keywords may also be an identifier, depending on context */
Identifier
    : tIdentifier    { $$ = $1; }
    | tDEFAULT       { ctx->last_token = tIdentifier; $$ = $1; }
    | tERROR         { ctx->last_token = tIdentifier; $$ = $1; }
    | tEXPLICIT      { ctx->last_token = tIdentifier; $$ = $1; }
    | tPROPERTY      { ctx->last_token = tIdentifier; $$ = $1; }
    | tSTEP          { ctx->last_token = tIdentifier; $$ = $1; }
```

It looks like that table has constants for colors. 

Can you try your patch with this:

```
'colors
Const red = 5
Const orange = 4
Const amber = 6
Const yellow = 3
Const darkgreen = 7
Const green = 2
Const blue = 1
Const darkblue = 8
Const purple = 9
Const white = 11
Const teal = 10
Const default = 0 ' <--- Add this
```

**Comment by francisdb** [comment]
@jsm174 updated with your better fix

Not that i fully understand why this works in windows and not on *nix

**Pull request merged**
