### PR TITLE
patch: DarkPrincess1.3.1

### PR DESCRIPTION
**Pull request by francisdb**
https://vpuniverse.com/files/file/8119-darkprincess-original-2020-v13-update-sound-files

I put the music files next to the table in `./music`

### CODE REVIEW

**Comment by zognic** [comment]
`UltraDMD.SetProjectFolder curDir & "\DarkPrincess.UltraDMD"` don't add the good path for the flexDMD

```log
[AssetManager::SetBasePath@41] Base path set to: /userdata/roms/vpinball/Darkprincess (Original 2020)/./DarkPrincess.UltraDMD/
```

**Comment by francisdb** [comment]
@zognic it's actually a valid path, just not normalized?

Works for me.

**Comment by zognic** [comment]
My bad I thought it was a wrong path

**Comment by zognic** [comment]
Do you know how the add the FlexDMD on the table with desktop mode ? (It works on the PixelCade)

**Comment by francisdb** [comment]
> Do you know how the add the FlexDMD on the table with desktop mode ? (It works on the PixelCade)

I use an external window. And this table is using UltraDMD, maybe something is different in that case?

**Pull request merged**
