### PR TITLE
patch: Iron Maiden (Original 2022) VPW 1.0.12

### PR DESCRIPTION
**Pull request by francisdb**
I'm currently stuck at a segfault

There is also a wine issue where this code does not work
```vbs
	dim vL, pL

	Execute ("set vL=v" & n.name)
	Execute ("set pL=p" & n.name)
```

`vL` and `pL` are not set

So I worked around that

In the end this table is not really playable without PinUP but might still be interesting to fix the issues

also affected by #32

### CODE REVIEW

**Comment by jsm174** [comment]
@francisdb:

```
	Execute ("set vL=v" & n.name)
	Execute ("set pL=p" & n.name)
```

I wonder if this would work instead:

```
	set vL = eval("v" & n.name)
        set pL = eval("p" & n.name)
```

I believe we had to do this somewhere in the light controller library.

**Comment by francisdb** [comment]
@jsm174 yes that works, was also able to remove some more commented code as more pup stubs are in place

**Comment by francisdb** [comment]
my patch generation code is also a bit broken regarding encoding, need to fix that

**Comment by francisdb** [comment]
encoding issues fixed

**Comment by jsm174** [comment]
@francisdb, @dekay 

I think I implemented most of `DatePart` and `DateDiff`: 
https://github.com/vpinball/vpinball/blob/7f3cb44aa317119959cf702fba77d242a12fa712/standalone/inc/wine/dlls/vbscript/global.c#L2647-L2773

Could you retry with this (and maybe halloween)

I think I'm still getting a VBS Overflow every once in a while, still trying to track down where that comes from.

**Comment by francisdb** [comment]
On first sight this runs properly, but only played 2 minutes.

What do you mean with `and maybe halloween`?

**Comment by jsm174** [comment]
@francisdb - Can we revisit to finally close this one?

**Comment by francisdb** [comment]
It plays fine but for my part this can be merged or closed. This table does not make a lot of sense without pup pack.

**Pull request closed without merging**
