### PR TITLE
patch: Pat Hand (Williams 1975) 1.5

### PR DESCRIPTION
**Pull request by francisdb**
https://vpuniverse.com/files/file/19831-pat-hand-williams-1975-15/

Asked the author to incorporate the patch in a next version at https://vpuniverse.com/forums/topic/10265-new-vp10-alert-pat-hand-williams-1975-15/

### CODE REVIEW

**Comment by EngineersNeedArt** [comment]
Curious Francis, why stand-alone needs VBS massaging?

**Comment by francisdb** [comment]
Because standalone (and possibly in the future vpinball) uses the wine vbscript engine and that implementation has some issues. I tried fixing this specific issue but it's beyond my skill level.

**Comment by francisdb** [comment]
Details on the remaining issues are kept here: https://github.com/vpinball/vpinball/tree/10.8.1/standalone#background

**Comment by francisdb** [comment]
Closing as the changes have been incorporated in the 1.5.1 release

**Pull request closed without merging**
