### PR TITLE
dmd: Megadeth (original)

### PR DESCRIPTION
**Pull request by toccata10**
The megadeth original table (https://vpuniverse.com/files/file/17512-megadeth-original/) works without any hack, but default config is to use a pup-pack (not supported in standalone). So, without this vbs modification: no music which makes the table super boring. These modifications will allow standalone users to enjoy this great table in all its glory with the music.

### CODE REVIEW

**Comment by francisdb** [comment]
Does the DMD work for you? Stays on game over here.

**Comment by toccata10** [comment]
It's a problem that appeared a few revisions of standalone ago (starting from ...(I don't remember, but old versions worked fine. It was more or less related to the new 10.8.1 branch)).
Seems solved with the latest action build from
(https://github.com/vpinball/vpinball/actions/runs/7212417685)

**Comment by toccata10** [comment]
By the way, do you mind checking if my eol are correct ?
I used unix2dos on the vbs files before the generate.sh
I'm wondering if my workflow is correct now.

**Comment by francisdb** [comment]
> It's a problem that appeared a few revisions of standalone ago (starting from ...(I don't remember, but old versions worked fine. It was more or less related to the new 10.8.1 branch)). Seems solved with the latest action build from (https://github.com/vpinball/vpinball/actions/runs/7212417685)

Reported here: https://github.com/vpinball/vpinball/issues/1276

**Comment by francisdb** [comment]
> By the way, do you mind checking if my eol are correct ? I used unix2dos on the vbs files before the generate.sh I'm wondering if my workflow is correct now.

```
vpx-standalone-scripts git:(master) git checkout dmd_megadeth 
branch 'dmd_megadeth' set up to track 'toccata10/dmd_megadeth'.
Switched to a new branch 'dmd_megadeth'
➜  vpx-standalone-scripts git:(dmd_megadeth) ✗ git status
On branch dmd_megadeth
Your branch is up to date with 'toccata10/dmd_megadeth'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Megadeth (original)/Megadeth (original).vbs.original

no changes added to commit (use "git add" and/or "git commit -a")
```

I fear the problem is in the fact that you upload through github instead of using a git client.

But you could try `dos2unix` as they are actually stored raw with `LF` in the repository.

**Comment by jsm174** [comment]
Hello. @francisdb @toccata10 - Is this ready to be merged?

**Comment by francisdb** [comment]
I can always fix newlines after merge, it's just a bit annoying.

**Comment by toccata10** [comment]
Closing in favor of #222 without end line problems

**Pull request closed without merging**
