### PR TITLE
patch: Munsters (Original 2020) 1.05

### PR DESCRIPTION
**Pull request by francisdb**
Not sure this table makes a lot of sense as it probably heavily relies on pup packs

Currently crashes vpinball

```
2023-10-04 10:12:20.692 INFO  [78767] [external_create_object@685] progid=PinUpPlayer.PinDisplay, hres=0x00000000
2023-10-04 10:12:20.692 INFO  [78767] [PinUpPlayerPinDisplay::B2SInit@230] Playlists loaded: file=/home/francisdb/vpinball/tables/The Munsters Pro (Stern 2019)/mmunsters/playlists.pup, size=35
2023-10-04 10:12:20.693 INFO  [78767] [PinUpPlayerPinDisplay::B2SInit@251] Triggers loaded: file=/home/francisdb/vpinball/tables/The Munsters Pro (Stern 2019)/mmunsters/triggers.pup, size=3
2023-10-04 10:12:20.693 INFO  [78767] [PinUpPlayerPinDisplay::B2SInit@272] Screens loaded: file=/home/francisdb/vpinball/tables/The Munsters Pro (Stern 2019)/mmunsters/screens.pup, size=20
2023-10-04 10:12:20.693 WARN  [78767] [PinUpPlayerPinDisplay::get_GetRoot@335] Not implemented
Table exited with unknown code
```

### CODE REVIEW

**Comment by toccata10** [comment]
As Pinup player improves, I wanted to try this table, but it crashes with:
```
2024-05-27 08:25:53.464 ERROR [13370] [CodeViewer::OnScriptError@1212] Script Error at line 467 : VBSE_PATH_NOT_FOUND
2024-05-27 08:25:53.464 ERROR [13370] [CodeViewer::AppendLastErrorTextW@3979] Runtime error: Line: 467, Character: 1, VBSE_PATH_NOT_FOUND
```

**Comment by francisdb** [comment]
@toccata10 thanks for the reminder, let me have a look at the patch now that pup pack stuff is more or less working

**Comment by francisdb** [comment]
Table is working here, however the pup pack is not

```
2024-05-27 09:23:21.977 WARN  [602518] [PUPPinDisplay::playresume@112] Not implemented: screenNum=4
```

Maybe @jsm174 can shed some light on this?

**Comment by toccata10** [comment]
To make it work, I had to change this line:
```   Folder=PupVideos & "\" &  cGameName & "\" ```
to ```    Folder="pupvideos\mmunsters\" ```
(it crashed otherwise)
Then it plays with the 2 screens config, but there's a scaling problem (at least on my 4k screen) + problem with special characters. But I remember I had also trouble with scaling when I tried this on windows (a long time ago...).
mmunsters-ss

**Comment by francisdb** [comment]
@toccata10 you are correct, my setup was just not picking up the pup pack. Fixed the patch.

`PupVideos=PuPlayer.getroot` seems to return `[table-root]` instead of  `[table-root]/pupvideos` 

And the missing mp3 support together with some label issues make this rather unplayable.

**Comment by jsm174** [comment]
I'll fix this 

> @toccata10 you are correct, my setup was just not picking up the pup pack. Fixed the patch.
> 
> `PupVideos=PuPlayer.getroot` seems to return `[table-root]` instead of `[table-root]/pupvideos`
> 
> And the missing mp3 support together with some label issues make this rather unplayable.

I'll fix this.

**Comment by francisdb** [comment]
It already got better with the updates from today. Also some newline issues.

image

image

**Comment by jsm174** [comment]
@francisdb - getroot is fixed so I think you can walk that change back

**Comment by francisdb** [comment]
Looks like this pup pack is also missing a third screen that plays videos in fulldmd mode

To put the Pup DMD screen in full screen update the screens.pup to have this line for DMD
`1,DMD,,,0,ForceOn,,"2,0,0,100,100"`

**Pull request merged**
