### PR TITLE
patch: Sonic The Hedgehog (Brendan Bailey 2005) VPX_(MOD)1.21

### PR DESCRIPTION
**Pull request by francisdb**
https://www.vpforums.org/index.php?app=downloads&showfile=17707

### CODE REVIEW

**Comment by francisdb** [comment]
I do wonder how to get the dmd to work on desktop, should check windows

**Comment by francisdb** [comment]
@jsm174 with the new code and `DMD=1` the dmd is visible

for my part this can be merged

image

**Comment by jsm174** [comment]
@francisdb - Cool. Before I merge this could you try one thing, just to prove / disprove a wine theory.

Could your try to remove the two outer parens?

ie, instead of:

```vbs
DisplayB2SText ((score(currentplayer)) &" " & "              BALL 2 ")
```

try:

```vbs
DisplayB2SText score(currentplayer) &" " & "              BALL 2 "
```

**Comment by francisdb** [comment]
@jsm174 also works

By the way it looks like horizontal scrolling big text is not working on the dmd. The text stays static. Is this a known issue?

**Comment by jsm174** [comment]
> By the way it looks like horizontal scrolling big text is not working on the dmd. The text stays static. Is this a known issue?

linux? mac? both?

**Pull request merged**
