### PR TITLE
Haunted House (Gottlieb 1982) 1.0

### PR DESCRIPTION
**Pull request by francisdb**

### CODE REVIEW

**Comment by jsm174** [comment]
Thanks!

**Comment by francisdb** [comment]
@jsm174  Do you know if there is a wine VBScript issue for this one?

**Comment by jsm174** [comment]
I assumed you tested it prior to submitting the PR. I can take a look.

**Comment by francisdb** [comment]
Yes, It's just a `Sub` `End Sub` on a single line that does not seem to be supported

**Pull request merged**
